services:
  typesense:
      ports:
        - 8108:8108
      image: typesense/typesense:28.0
      restart: on-failure
      volumes:
        - typesense-data:/data
      command: '--data-dir /data --api-key=cvcvbyrrqhwpatfdjlcf --enable-cors'

  server:
    profiles:
      - dev
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgres://postgres:example@postgres:5432/postgres
      - TYPESENSE_API_KEY=cvcvbyrrqhwpatfdjlcf
      - TYPESENSE_HOST=typesense

  postgres:
    ports:
      - 5432:5432
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example

volumes:
  typesense-data:
  postgres-data:
