# fly.toml app configuration file generated for ei-search-dawn-brook-2805 on 2023-12-18T22:28:47-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ei-search-dawn-brook-2805"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
