# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  typesense:
    ports: !reset []
  postgres:
    ports: !reset []
