# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  server:
    container_name: ei-search-frontend
    profiles: !reset []
    networks:
      - caddy
      - default
    ports: !reset []
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:example@ei-search-postgres:5432/postgres
  typesense:
    ports: !reset []
    restart: always
    networks:
      - default
  postgres:
    container_name: ei-search-postgres
    ports: !reset []
    restart: always
    networks:
      - default

networks:
  caddy:
    external: true
